project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
        
  page-footer:
    right: "&copy; 2024, Caitlin Ree"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto


